server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: healthcare-blockchain-single-node

  datasource:
    url: jdbc:mysql://localhost:3306/fyp
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    enabled: false

  # Single Node Profile
  profiles:
    active: single-node

# =====================================================
# SINGLE NODE CORDA CONFIGURATION
# =====================================================

corda:
  enabled: true
  mode: single-node

  # Single HealthcareNode connection
  host: localhost
  rpc:
    port: 10006
    username: healthcare
    password: healthcare123

  # Single node network (combines all roles)
  network:
    healthcare-node: "O=HealthcareNode,L=NewYork,C=US"

  # Node capabilities (what this single node can do)
  capabilities:
    - hospital-services
    - patient-registry
    - regulatory-oversight
    - notary-services

# Blockchain Configuration
blockchain:
  enabled: true
  mode: real-single-node
  fallback-mode: false
  timeout: 30000
  retry-attempts: 3

  # Single node specific settings
  single-node:
    name: "HealthcareNode"
    roles: ["Hospital", "PatientRegistry", "Regulator", "Notary"]
    all-in-one: true

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.healthcare: DEBUG
    net.corda: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/healthcare-single-node.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,corda
  endpoint:
    health:
      show-details: always
    corda:
      enabled: true

# =====================================================
# PROFILE-SPECIFIC CONFIGURATIONS
# =====================================================

---
# Single Node Profile
spring:
  config:
    activate:
      on-profile: single-node

  datasource:
    # Use H2 for single node development
    url: jdbc:h2:mem:healthcare_single;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.healthcare: DEBUG
    net.corda: DEBUG
    org.springframework.web: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

corda:
  rpc:
    username: ${CORDA_RPC_USERNAME:healthcare}
    password: ${CORDA_RPC_PASSWORD:healthcare123}

blockchain:
  timeout: 60000
  retry-attempts: 5

logging:
  level:
    com.healthcare: INFO
    net.corda: WARN
    org.springframework: WARN